openapi: 3.0.3
info:
  title: Wallet project
  description: Wallet project
  version: 1.1.1
servers:
  - url: 'https://wallet.com'
paths:
  /account:
    get:
      summary: Retrieve the list of accounts
      responses:
        200:
          description: OK
          content:
            application/json:
              example:
                - account_id: 1
                  customer_name: Rakoto
                  balance: 1000.00
                  currency:
                    currency_id: 1
                    currency_name: US Dollar
                    currency_code: "USD"
    post:
      summary: create an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        200:
          description: Account created successfully
          content:
            application/json:
              example:
                account_id: 2
                customer_name: Rasoa
                balance: 0.00
                currency_id: 1
  /transaction:
    get:
      summary: Retrieve the list of all transactions
      responses:
        200:
          description: OK
          content:
            application/json:
              example:
                transaction_id: 1
                account_id: 1
                amount: 100
                transaction_date: "2023-12-03"
                description: purchase
    post:
      summary: carry out a transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        200:
          description: Transaction created successfully
          content:
            application/json:
              example:
                transaction_id: 2
                account_id: 1
                amount: 50.00
                transaction_date: "2023-12-03"
                description: expense
  /currency:
    get:
      summary: Retrieve the list of all currency
      responses:
        200:
          description: OK
          content:
            application/json:
              example:
                - currency_id: 1
                  currency_name: US Dollar
                  currency_code: "USD"
                - currency_id: 2
                  currency_name: Euro
                  currency_code: "EUR"
components:
  schemas:
    Account:
      type: object
      properties:
        customer_name:
          type: string
        balance:
          type: number
        currency:
          $ref: '#/components/schemas/Currency'
    Transaction:
      type: object
      properties:
        account_id:
          type: integer
        amount:
          type: number
        date:
          type: string
          format: date
        description:
          type: string
    Currency:
      type: object
      properties:
        currency_id:
          type: integer
        currency_name:
          type: string
        currency_code:
          type: string